spring:
  datasource:
    url: jdbc:postgresql://usersdb.cl0e0g0ququt.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  # Optional: Show SQL statements in the console
    format-sql: true  # Optional: Pretty print SQL